TEALSK12/apcsa-public

make.cmd

This time from a branch of the original repo.

Test for PRs

---

README.md

Fix typo causing 404 error on Curriculum-Map.md file

---

curriculum/Assets.md

Move Assets.md to apcsa-public.

Move Assets.md to apcsa-public/curriculum

---

curriculum/Assets.md

Need mechanism to bulk grant access to GitHub Team

Remote link to instructor repository

---

curriculum/README.md

Addresses GitBook Discussion topic #9: https://www.gitbook.com/book/tealsk12/ap-computer-science-a/discussions/9.

Add link to UDL located in Additional Resources

---

curriculum/Unit3/Lesson-304.md

Input is not covered until later in Unit

Remove prompting user in exercise 3

---

curriculum/Unit3/Lesson-302.md

@hollasch Added a missing method writeChars to lesson 3.02.

Add missing method

---

curriculum/Unit4/Lesson-405.md

The loop should be decremented instead of incremented

Change loop to decrement

---

curriculum/Unit1/Lesson-103.md

1.3 Lesson update learning objective

---

curriculum/README.md

GitBook is mysteriously failing builds again, thought it might be
related to this section I just approved a PR for. In any event, this
simplifies the Markdown for plaintext readability.

Simplify link to Barron's APCSA review book

---

curriculum/README.md

Updated Curriculum map to a working link

Updated link to Curriculum Map

---

curriculum/SUMMARY.md

Adding the new labs to the summary file

Aspiece patch 4

---

curriculum/Unit2/Lesson-206.md

The lesson 2.6 description includes a stale bit from lesson 2.5 without much connection to nested loops. Removing that here.

Remove dupe section from 2.5

---

curriculum/README.md

Remove AP Squad

---

.gitignore
README.md
curriculum/CONTRIBUTING.md

Also see #179 which is outside the scope of this change, but was discovered because of it.

Add info about how to use GitBook to preview the repo locally

---

curriculum/README.md

Endorsement requirement for each computational thinking skill to be linked to a particular example from the curriculum.
Also tweaked skill list items to now lead with A/B/C...

Connect skill to specific example in curriculum

---

curriculum/Unit2/Lesson-208a.md

Broke up classroom procedure and introduction. 
It says that students can use other songs, but "option 1" and "option 2" are really specific to the individual songs. I modified the options so they appeared more general, I still think you might need a more generic option... What if you had them count/ print the words in each line?

Edited for clarity and to apply generally to more song options. 

---

docs/Unit3/Lesson-304.md.html

Using Mathjax. For tips, see
https://artofproblemsolving.com/wiki/index.php/LaTeX:Symbols

An example using math equations in Markdeep

---

docs/Unit3/Lesson-304.md.html

Reverts TEALSK12/apcsa-public#223

Revert "An example using math equations in Markdeep"

---

curriculum/SUMMARY College Board.md
curriculum/Unit3-Map-CB.md
curriculum/Unit4-Map-CB.md
curriculum/Unit5-Map-CB.md
curriculum/Unit8-Map-CB.md

Move boolean from unit 4 to 3
Move picture lab from unit 5 to 8

Fixes college board

---

curriculum/CA-README.md
curriculum/README.md
curriculum/Unit1/Lesson-1XX.md

- Added title "Aligning TEALS APCSA Teaching Resources with the BC Curriculum" to CA-README.md and included descriptions
- Added link to CA-README.md under "Using this curriculum" in README.md
- Correctly incorporated updates from the CA-2018-Aug branch to Unit 1 alternative project

BC 2020 merge - First Pass
